# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

config:
  send_anonymous_usage_stats: False


startup-ab-bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: startup_alberta # You can also use "schema" here
      threads: 4
      timeout_seconds: 300
      location: US # Optional, one of US or EU
      priority: interactive
      retries: 1

    dtspec:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: startup_alberta # You can also use "schema" here
      threads: 4
      timeout_seconds: 300
      location: US # Optional, one of US or EU
      priority: interactive
      retries: 1
