version: 2

sources:

  - name: raw
    schema: startup_alberta
    tables:
      - name: raw_companies
      - name: raw_companies_fundings
      - name: raw_companies_fundings_items
      - name: raw_companies_fundings_items_investors
