version: 2

models:
  - name: stg_companies
    description: "Alberta based startups and scaleups. Company names and details. Can be used with investors and investment tables."
    columns:
      - name: id
        description: "Unique company id (defined by Startup Alberta website)"
        tests:
          - unique
          - not_null
      - name: name
        description: "Company name"
        tests:
          - not_null
      - name: growth_stage
        description: "Stage of growth of company: seed/early growth/late growth"
      - name: created_at
        description: "Date company was created at."
      - name: total_funding_to_date
        description: "Total amount of funding (USD) raised as of last update."
      - name: updated_at
        description: "Date record last updated at."
      

  # - name: stg_orders
  #   columns:
  #     - name: order_id
  #       tests:
  #         - unique
  #         - not_null
  #     - name: status
  #       tests:
  #         - accepted_values:
  #             values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  # - name: stg_payments
  #   columns:
  #     - name: payment_id
  #       tests:
  #         - unique
  #         - not_null
  #     - name: payment_method
  #       tests:
  #         - accepted_values:
  #             values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
